import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Paste a Lead",
  description:
    "Privacy policy for Paste a Lead — how we handle the lead messages you paste into the app.",
};

const CONTACT_EMAIL = "james@leadqualify.co.uk";;
const LAST_UPDATED = "6 May 2026";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white text-slate-900">
      <section className="mx-auto max-w-3xl px-6 py-16 md:px-8 md:py-24">
        <p className="mb-4 inline-flex rounded-full border border-slate-200 px-3 py-1 text-sm text-slate-600">
          Privacy Policy
        </p>

        <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
          Privacy Policy
        </h1>

        <p className="mt-4 text-sm text-slate-500">
          Last updated: {LAST_UPDATED}
        </p>

        <div className="mt-10 space-y-10 text-base leading-7 text-slate-700">
          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              About Paste a Lead
            </h2>
            <p className="mt-3">
              Paste a Lead (&ldquo;the app&rdquo;, &ldquo;we&rdquo;,
              &ldquo;us&rdquo;) lets you paste a lead message — for example, an
              email, DM, or web enquiry — and get a quick assessment of whether
              the lead looks qualified, what information is missing, and a
              suggested reply.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              What you provide
            </h2>
            <p className="mt-3">
              The text you paste into the app is the only content we process to
              generate a result. Please do not paste content you are not
              comfortable sharing — for example, sensitive personal data,
              payment details, passwords, or confidential business information.
              You are responsible for ensuring you have the right to share any
              message you paste.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              How your text is processed
            </h2>
            <p className="mt-3">
              To produce a qualification result, the text you paste may be sent
              to a third-party AI service (such as a large language model
              provider) for processing. That provider processes the text to
              return a response and may apply its own data-handling policies.
            </p>
            <p className="mt-3">
              We do not use your pasted content to train AI models, and we do
              not sell your data to third parties.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              Data storage
            </h2>
            <p className="mt-3">
              We aim to keep data storage to a minimum. The text you paste is
              processed to generate a result and is not retained on our servers
              beyond what is required to return that result. Some recent
              activity may be stored locally on your device so you can review
              past results — this stays on your device and you can clear it at
              any time.
            </p>
            <p className="mt-3">
              We may keep limited, non-identifying technical logs (such as
              error reports and aggregate usage counts) to keep the service
              running and to fix bugs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              No professional advice
            </h2>
            <p className="mt-3">
              Paste a Lead provides automated suggestions for informational
              purposes only. Results are generated by AI and may be incomplete,
              outdated, or wrong. We make no guarantee as to the accuracy,
              reliability, or suitability of any output.
            </p>
            <p className="mt-3">
              Nothing produced by the app is financial, tax, legal, accounting,
              or investment advice. Do not rely on the app for any decision
              that requires professional judgement. Always consult a qualified
              professional before acting on anything you read here.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              Children
            </h2>
            <p className="mt-3">
              Paste a Lead is not directed at children under 13, and we do not
              knowingly collect personal information from children.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              Changes to this policy
            </h2>
            <p className="mt-3">
              We may update this policy from time to time. When we do, we will
              update the &ldquo;Last updated&rdquo; date at the top of this
              page. Continued use of the app after changes means you accept the
              updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">Contact</h2>
            <p className="mt-3">
              If you have any questions about this policy or how your data is
              handled, please contact us at{" "}
              <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="font-medium text-slate-900 underline underline-offset-4 hover:opacity-80"
              >
                {CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>
        </div>
      </section>
    </main>
  );
}
