import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Paste a Lead",
  description:
    "Terms of service for Paste a Lead — the rules and disclaimers that apply when you use the app.",
};

const CONTACT_EMAIL = "james@leadqualify.co.uk";;
const LAST_UPDATED = "6 May 2026";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-slate-900">
      <section className="mx-auto max-w-3xl px-6 py-16 md:px-8 md:py-24">
        <p className="mb-4 inline-flex rounded-full border border-slate-200 px-3 py-1 text-sm text-slate-600">
          Terms of Service
        </p>

        <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
          Terms of Service
        </h1>

        <p className="mt-4 text-sm text-slate-500">
          Last updated: {LAST_UPDATED}
        </p>

        <div className="mt-10 space-y-10 text-base leading-7 text-slate-700">
          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              1. Agreement
            </h2>
            <p className="mt-3">
              These Terms of Service (&ldquo;Terms&rdquo;) govern your access to
              and use of Paste a Lead (&ldquo;the app&rdquo;,
              &ldquo;we&rdquo;, &ldquo;us&rdquo;). By using the app, you agree
              to these Terms. If you do not agree, please do not use the app.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              2. What the app does
            </h2>
            <p className="mt-3">
              Paste a Lead provides automated lead qualification assistance.
              You paste a lead message — for example, an email, DM, or web
              enquiry — and the app returns a suggested qualification status, a
              score, reasons, missing information, and a draft reply.
            </p>
            <p className="mt-3">
              The app is a productivity tool. It does not replace your own
              judgement, sales process, or professional expertise.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              3. Acceptable use
            </h2>
            <p className="mt-3">You agree not to use the app to:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>
                Submit content you do not have the right to share, or content
                that is unlawful, infringing, or harmful.
              </li>
              <li>
                Submit sensitive personal data, payment details, credentials,
                or confidential information you are not authorised to share.
              </li>
              <li>
                Attempt to reverse engineer, disrupt, or interfere with the
                app, its security, or the underlying services.
              </li>
              <li>
                Use the app to generate spam, harassment, or deceptive content.
              </li>
              <li>
                Use the app in any way that violates applicable laws or the
                terms of any third-party service it relies on.
              </li>
            </ul>
            <p className="mt-3">
              You are solely responsible for the content you submit and for how
              you use any output the app produces.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              4. No professional advice
            </h2>
            <p className="mt-3">
              Output from the app is generated by AI and is provided for
              informational purposes only. It is not financial, tax, legal,
              accounting, investment, or any other form of professional advice.
              Always consult a qualified professional before acting on anything
              the app produces.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              5. Accuracy and availability
            </h2>
            <p className="mt-3">
              The app uses AI services that can produce results that are
              incomplete, outdated, or incorrect. We do not warrant that any
              output is accurate, reliable, or fit for a particular purpose.
            </p>
            <p className="mt-3">
              The app is provided on an &ldquo;as is&rdquo; and &ldquo;as
              available&rdquo; basis. We may change, suspend, or discontinue
              all or part of the app at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              6. Your responsibility for decisions
            </h2>
            <p className="mt-3">
              You are responsible for any decisions you make and any actions
              you take based on the app&rsquo;s output, including replies you
              send, leads you accept or reject, and business or financial
              choices you make. You should review and verify any output before
              acting on it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              7. Limitation of liability
            </h2>
            <p className="mt-3">
              To the fullest extent permitted by law, Paste a Lead and its
              operators are not liable for any indirect, incidental, special,
              consequential, or punitive damages, or for any loss of profits,
              revenue, data, goodwill, or business opportunities, arising out
              of or related to your use of the app or any decision made using
              its output.
            </p>
            <p className="mt-3">
              Nothing in these Terms excludes or limits any liability that
              cannot be excluded or limited under applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              8. Third-party services
            </h2>
            <p className="mt-3">
              The app relies on third-party services, including AI providers,
              to function. Those services have their own terms and policies,
              and we are not responsible for their performance or behaviour.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              9. Privacy
            </h2>
            <p className="mt-3">
              Your use of the app is also subject to our{" "}
              <a
                href="/privacy"
                className="font-medium text-slate-900 underline underline-offset-4 hover:opacity-80"
              >
                Privacy Policy
              </a>
              , which explains how we handle the content you paste.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              10. Changes to these Terms
            </h2>
            <p className="mt-3">
              We may update these Terms from time to time. When we do, we will
              update the &ldquo;Last updated&rdquo; date above. Continued use
              of the app after changes means you accept the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              11. Termination
            </h2>
            <p className="mt-3">
              We may suspend or terminate your access to the app at any time
              if you breach these Terms or use the app in a way that could
              cause harm to us, other users, or third parties.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900">
              12. Contact
            </h2>
            <p className="mt-3">
              Questions about these Terms? Contact us at{" "}
              <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="font-medium text-slate-900 underline underline-offset-4 hover:opacity-80"
              >
                {CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>
        </div>
      </section>
    </main>
  );
}
